os: linux
dist: bionic

jobs:
  fast_finish: true
  include:
    - python: "3.7"
      language: python
      env: TOXENV=lint

    - python: "3.7"
      language: python
      env: TOXENV=py37

    - python: "3.8"
      language: python
      env: TOXENV=py38

    - language: minimal
      env: TOXENV=py38
      before_install:
        # deadsnakes is not allowed on bionic at the moment via the `apt` addon
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get -q update
        - sudo apt-get -y install python3.8 python3.8-dev python3.8-venv
        - virtualenv -p python3.8 ~/virtualenv
        - source ~/virtualenv/bin/activate
        - python --version

install: pip install -U setuptools tox coveralls
script: tox
after_success: coveralls
